project:
  type: website

website:
  title: "R for Reproducibility"
  twitter-card: true
  navbar:
    right:
      - icon: home
        href: https://daniela-palleschi.github.io/
        text: D. Palleschi
      - icon: github
        href: https://github.com/daniela-palleschi/r4repro_SoSe2024
        aria-label: Source Code
      - icon: life-preserver
        href: https://moodle.hu-berlin.de/course/view.php?id=127770
        aria-label: Course Moodle
  sidebar:
    contents:
      - slides/01-open_science/open_science.qmd
      - slides/02-replication_crisis/replication_crisis.qmd
      - slides/03-reproducibility/reproducibility.qmd
      - slides/04-rprojects/rprojects.qmd
      - slides/05-literate_programming/lit_programming.qmd
      - slides/06-data_wrangling/wrangling.qmd
      - slides/07-tables/tables.qmd
      - slides/08-data_viz/data_viz.qmd
      - slides/09-packages/packages.qmd

    # - references.qmd
# 
# 
  

bibliography: references.bib
csl: apa.csl

crossref:
  exm-prefix: ex.   # (default is "Figure")
  # labels: alpha a        # (default is arabic)
  # subref-labels: alpha t # (default is alpha a)

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-tools: true
    css: styles.css
    toc: true
    include-after-body: custom.html
    page-layout: full
    self-contained: true
execute:
  eval: true
  echo: true
  message: false
  error: false
  warning: false
  fig-align: "center"
  fig-asp: .618



